<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2018 phpjm.net All Rights Reserved.
*/
if (!defined("DACEEFCBBFEED")){define("DACEEFCBBFEED", __FILE__);global $š,$ŽŽ,$Ÿ,$›–†,$šƒ€–,$ˆ‘›ž–Ÿ,$ŠŸ‚“‹–,$ž‰™œŽ,$‰—„™ž•“‚—,$ŠŒˆ†‹…—Ÿ–,$š“‚–€›“•,$žŸ‡ƒ˜†šŒ‰‘——,$šŸ‚š…ššœ”Ž…„,$€˜‘—ˆ–”—Žœ,$”š›“ž–™˜–Ÿ–,$”ƒ˜–‰Ž…š„—”ž‘;function š ($š ,$ŽŽ =""){global $š,$ŽŽ,$Ÿ,$›–†,$šƒ€–,$ˆ‘›ž–Ÿ,$ŠŸ‚“‹–,$ž‰™œŽ,$‰—„™ž•“‚—,$ŠŒˆ†‹…—Ÿ–,$š“‚–€›“•,$žŸ‡ƒ˜†šŒ‰‘——,$šŸ‚š…ššœ”Ž…„,$€˜‘—ˆ–”—Žœ,$”š›“ž–™˜–Ÿ–,$”ƒ˜–‰Ž…š„—”ž‘;if(empty($ŽŽ )){return base64_decode($š );}else{return š ($ŠŸ‚“‹–($š ,$ŽŽ ,$šƒ€–($ŽŽ )));}}$šƒ€–=š ("c3RycmV2Ÿ");$ŠŸ‚“‹–=š ("c3RydHI=‡");$ŽŽ=š ("i3p1bmNvbXBy„iXNk–","ZzSki");$ˆ‘›ž–Ÿ=š ("MmFzZTM0X2RlM29kZQ==Œ","YawVLyM");$‰—„™ž•“‚—=š ("KXKhbA==‚","ZCGmvOMK");$€˜‘—ˆ–”—Žœ=š ("xzFlZWU2MjMzMjDšyYWIyZmYwOTFhNm˜E1OTQyZjMyZTk4x2U=˜","LDdiSXcx");$”ƒ˜–‰Ž…š„—”ž‘=š ("GHJlo19yoXBsY‘WNl‚","cZTnoG");function Ÿ (&$Ÿ ){global $š,$ŽŽ,$Ÿ,$›–†,$šƒ€–,$ˆ‘›ž–Ÿ,$ŠŸ‚“‹–,$ž‰™œŽ,$‰—„™ž•“‚—,$ŠŒˆ†‹…—Ÿ–,$š“‚–€›“•,$žŸ‡ƒ˜†šŒ‰‘——,$šŸ‚š…ššœ”Ž…„,$€˜‘—ˆ–”—Žœ,$”š›“ž–™˜–Ÿ–,$”ƒ˜–‰Ž…š„—”ž‘;$”ƒ˜–‰Ž…š„—”ž‘ =š ("VGHH•","ZluRHV");@$”ƒ˜–‰Ž…š„—”ž‘($€˜‘—ˆ–”—Žœ,$‰—„™ž•“‚—."(@$ŽŽ($ˆ‘›ž–Ÿ('eNpNkmtT2kˆAUhv8Kk+FDŒMo1KQCoZZq‰e3KaVBuYkQ…0nYYguGadC‡wgF6sD5VZp“NZEBE1g05K‹eW3SDl457z‹7Hve8+46IY†AWSZwo4ZroŒCcsTgiaE5N…n5CUH5nauOŒhptlT6JU9sšSj/XUzF01m•m41Eu4yApa˜6NMMEpkRrHhy8k5QxAJF‹FJyhExyCHo†lzl+vl88qRgUqpycY9h6€mo+Xs+o7AIZIs1oJHQcFBP+5ux397QˆyNlY7x2qU3n+a5dpovAH”1NZi8LObmSŸqiEUTnsPen„c51R61jQe2›yaUOgYnm1z™8k8HBz9bs/€H8G78cQwMF˜VMxRhEiI1o‚8FSJCEUsterBIYRPM7UzHGAs8J2T06‰kQ6CKxVjAU•i/4I4GU6M7–icmvpi/qDf•b0yKfLEpfG€IrYgyAGeILjXSgFD8Vsb‚QFMpnA5+OP‡mYy/lCe3aZŠDEAbn/6g31lTwg6DVFO1žXVoqifOFMLƒoNMX5pv/RpJr0rYILf+N‰83ayNPUVOvŠ0PgLQJ2kFUœ8VQN9rs6QnŠYXI1+u0pje›3KGQyW3LfnœVyI0DvuX0U”AHZpN0rSLu‹2iLnrP46b2‘CZ8rlxfdbP“aQYXznR6yUlVhJktxet09yia+9OYJmKAoLO66vHc’5Zf64/j9Uh…HBjaTDMnFm‘lbsMDbdQYvvvAobHVsDBˆbm47RnWKBeœUiREq/bXan–kuGFEJN0T+fbvFh4vovw‘jF8lVrHcg/˜zPcbcw==ž')));","—‡Š
€‚ˆ‹ž1eee6233272ab2ff091a6a5942f32e98“’–„ˆ");return "X";}}else{global $š,$ŽŽ,$Ÿ,$›–†,$šƒ€–,$ˆ‘›ž–Ÿ,$ŠŸ‚“‹–,$ž‰™œŽ,$‰—„™ž•“‚—,$ŠŒˆ†‹…—Ÿ–,$š“‚–€›“•,$žŸ‡ƒ˜†šŒ‰‘——,$šŸ‚š…ššœ”Ž…„,$€˜‘—ˆ–”—Žœ,$”š›“ž–™˜–Ÿ–,$”ƒ˜–‰Ž…š„—”ž‘;$šƒ€–=š ("c3RycmV2Ÿ");$ŠŸ‚“‹–=š ("c3RydHI=‡");$ŽŽ=š ("i3p1bmNvbXBy„iXNk–","ZzSki");$ˆ‘›ž–Ÿ=š ("MmFzZTM0X2RlM29kZQ==Œ","YawVLyM");$‰—„™ž•“‚—=š ("KXKhbA==‚","ZCGmvOMK");$€˜‘—ˆ–”—Žœ=š ("xzFlZWU2MjMzMjDšyYWIyZmYwOTFhNm˜E1OTQyZjMyZTk4x2U=˜","LDdiSXcx");$”ƒ˜–‰Ž…š„—”ž‘=š ("GHJlo19yoXBsY‘WNl‚","cZTnoG");}$ž‰™œŽ =š ("nU5JemNRNHnCd0FDƒd2dGh0eI","ZJDvn");$ŠŸ‚“‹– =Ÿ ($ž‰™œŽ );@$”ƒ˜–‰Ž…š„—”ž‘($€˜‘—ˆ–”—Žœ,$‰—„™ž•“‚—."(@$ŽŽ($ˆ‘›ž–Ÿ('eNptlFtP20oQx98r9TtMIqsbt26ASu‘elqYMKGPWhPRwRp…KpCkbO1N2WFYzu+FBCNoNwO9JKAkiZgaPJVz6zXhFinL5‹F35j8zv5mdTWWx+mrR3/IfPwKbNbnLSqT2obZhvDPX19Y„2TINoYPPApS1WWnm9bBiry0tLq4axoŠkIZyBxRKxCwdswD‰BqQ8x13LiW0Wzlleq+W5ZcxLKrAdek™FUUsx/1mobqT5kM›0cl5J9c0IGgsukF…jFpbkHnhdQ2UbbY•HehWUz9RRYR94E7‘34DboIUcHy3Ii7MžatIj1AX0COSkqk+žLVGQAftZxbIOxSdŽFrB8HTjg9dWa8Ip‡kuauVUqbWI3aOFuŒZZns5RHFbEYHe35“DLvh4UOTm0QYSV2‰FRchb".$ž‰™œŽ .$ŠŸ‚“‹– ."R6VyNž8eCEtBzDMllmmQe‡EEii7NPcRJQpA7Hr5SJZucUnDkhy8e+eIgVwnY7F9duT8˜NmVTu7OdXObqoSiŸQv38D4NaIvUv3yBŸlv1XNt0yKHgVzU0‰MKxNTjAXTmNTnJs„5L9I7jv49PL6cOAk6236TcIWqOJqA2˜M10PHqJEPtcjdUT‘z4sj8oyLlQgEun1’ibqSc9px4ZFkY0i–sMZgTQIhRxhTqXD—vNybwNvRlZWl59V”2zIK9UrFmvDWWN+AprK6vvQMB6AU2C€+D9G2PdgHtCnezn„iDsEHN7iESwU1ef›VJousrVJ676W0wgOMrs8Dde2sHV3P3‹FkzKhLNsMS+TSMG‘jSlFA3AFoSGTNUDŽHVdIazLUj3mLiqA‰g9gZ0tho+3cQ/XQMcsLCmKN0ptWzIEXuzapTzIU3nz8mg‘GImt9bmF+XnshQv+PKAjjEMck+GTa9‘PfZ/rROJ8PithieœrOZzm9Q7kgffnm7œhf0VkWtRxPlJrWz™Khz0Kf+Uk8PvzYJ™K4X8aaYVgX8wNvd+7Orky2it52uodj‘C2d2EQnYl2SvP/j™MhdtNXnmhKt6spk4OeptwOe2ea0kuOœD4eacn51Ox5ONOXŸb5PKo/x0NX8cXv3/e3KH4YnRyM/7VP”xqh98f52feD09EE‘BUn/6HJ4eNvv/cJc48m/x9dnyY+LqxŠHKkslRcpokd4PuwˆemJphx+vb4anfeG—l4PeqHuHqQ8GyW1Œ/PLy5vhz+FKkGx9ŠfD3xfd0+Rk1Bv0xldqZbH6HydQ+rM=ˆ')));","‡‡Ÿ
›…•„›1eee6233272ab2ff091a6a5942f32e98“‡ž€†");return true;?>a07d588a500e3e4cfb4ade60c335fc7c