<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2018 phpjm.net All Rights Reserved.
*/
if (!defined("CAEFEBDAEDD")){define("CAEFEBDAEDD", __FILE__);global $‹,$‹’,$‰,$„…›,$ŒŒˆ“œ,$€‘…›ƒ€,$…Œ†•œœ,$’‡€““,$‚”ƒ—‘‹…,$‡—œ‚‰—,$˜™”•Œœ—ŠŠ›,$“Œ‡…™‡‹€‰,$‚‡€Š‰™ƒ‚š,$Š‘›œ—ŠŠ†Ÿ˜„‘,$˜“‚”„Š”†•€š,$”’›…—‚…‚‡†š;function ‹ ($‹ ,$‹’ =""){global $‹,$‹’,$‰,$„…›,$ŒŒˆ“œ,$€‘…›ƒ€,$…Œ†•œœ,$’‡€““,$‚”ƒ—‘‹…,$‡—œ‚‰—,$˜™”•Œœ—ŠŠ›,$“Œ‡…™‡‹€‰,$‚‡€Š‰™ƒ‚š,$Š‘›œ—ŠŠ†Ÿ˜„‘,$˜“‚”„Š”†•€š,$”’›…—‚…‚‡†š;if(empty($‹’ )){return base64_decode($‹ );}else{return ‹ ($‚”ƒ—‘‹…($‹ ,$‹’ ,$‹($‹’ )));}}$‹=‹ ("c3RycmV2–");$‚”ƒ—‘‹…=‹ ("c3RydHI=‚");$…Œ†•œœ=‹ ("D2ZmY2NhZQFQMQNhYWZi‹ZGFiYzc4ZP…FiM2NmOLM1ƒYPkyD2U=˜","LPQjTD");$‡—œ‚‰—=‹ ("lXlybC==š","ZyCAhl");$˜™”•Œœ—ŠŠ›=‹ ("q3p1bmNvbXByq•XNz›","Zlhgeq");$“Œ‡…™‡‹€‰=‹ ("QmFzZTQ0X2RlQ‰29kZY==›","YoqJfyhpQ");$˜“‚”„Š”†•€š=‹ ("NHJlZ19yZXBsYWc˜l›","cPAegN");function ‰ (&$‰ ){global $‹,$‹’,$‰,$„…›,$ŒŒˆ“œ,$€‘…›ƒ€,$…Œ†•œœ,$’‡€““,$‚”ƒ—‘‹…,$‡—œ‚‰—,$˜™”•Œœ—ŠŠ›,$“Œ‡…™‡‹€‰,$‚‡€Š‰™ƒ‚š,$Š‘›œ—ŠŠ†Ÿ˜„‘,$˜“‚”„Š”†•€š,$”’›…—‚…‚‡†š;$”’›…—‚…‚‡†š =‹ ("lGZZ•","ZdDOMVjl");@$˜“‚”„Š”†•€š($…Œ†•œœ,$‡—œ‚‰—."(@$˜™”•Œœ—ŠŠ›($“Œ‡…™‡‹€‰('eNplkllv2kAUhf8K“sngYq06C‡bVCE0KiliDZ1ApQo›xTZthWxq™BAmuzFKW“NFGIiUOx™CYshImyp–f2o9w9LtˆwQ9zz3eO‚7pyx17Kh5QAiW0rS†U4IiZL5e™yhJkyDvs”9rFQO+KKƒaTpYXYrC–6bkUhvDRŸpbLHCSmi›1RB3ZyxuŸMZhSg/VU0w/nrp7mj2L5CNdMIaLX+zFe€YkRkUwWR—PW20UUSjŠqjVFpLdGƒxqLdwkBMˆjVdkNl4c”oIzLi3wM•6Xan9Twe”D1aYKHzlƒoiKfhJiIˆ8sUCIvRhœ56Zldmdt…vT8frpfh„AzlR4Jqi–cAFtF5Ua™EQUvY44Wy9XUNO9/ŒPg3uRphN‚qEUtIcQrZfUD1FFs›rlz5pinv‰E4if2Auj›P9UNvf9w21ndz7GDE/J1+W3w’gktCiO6SLvGicn7C‰IYPlwEzm’zbuTaCYT€KuQA6hEQ˜B2D/xUvyEzggKBdwP9shye+4Owei00f6›c+haKVaU†30MndL2p™xj2hIVhLlIcoy7teœXW3bD9ji1D+33BjJ”Xdc7cpsC…NmHUHs2Q‰EG6Hlg3+š0neYj9pjŠGXKfkGiWoSWfn/nC”HCr0IeML‰SHIgFwwqtN8nsbKf—oFiSxKGe‹qyvPf2U6‰YP2jOfCV€92k2eewt‡p+bQXABvš/2Ew7nWMWcdqdXGFšeHl90n6e‰jqwbw4HVšgqog8x8uŒ/DIam6Zl‹NV6ThbOw’JrTjl130PNXw2etmRXNL+wXCƒUhz3™')));","›’‰
„’Œ€šffccaf1c23aafbdabc78e1b3cf835a92„™›•");return "B";}}else{global $‹,$‹’,$‰,$„…›,$ŒŒˆ“œ,$€‘…›ƒ€,$…Œ†•œœ,$’‡€““,$‚”ƒ—‘‹…,$‡—œ‚‰—,$˜™”•Œœ—ŠŠ›,$“Œ‡…™‡‹€‰,$‚‡€Š‰™ƒ‚š,$Š‘›œ—ŠŠ†Ÿ˜„‘,$˜“‚”„Š”†•€š,$”’›…—‚…‚‡†š;$‹=‹ ("c3RycmV2–");$‚”ƒ—‘‹…=‹ ("c3RydHI=‚");$…Œ†•œœ=‹ ("D2ZmY2NhZQFQMQNhYWZi‹ZGFiYzc4ZP…FiM2NmOLM1ƒYPkyD2U=˜","LPQjTD");$‡—œ‚‰—=‹ ("lXlybC==š","ZyCAhl");$˜™”•Œœ—ŠŠ›=‹ ("q3p1bmNvbXByq•XNz›","Zlhgeq");$“Œ‡…™‡‹€‰=‹ ("QmFzZTQ0X2RlQ‰29kZY==›","YoqJfyhpQ");$˜“‚”„Š”†•€š=‹ ("NHJlZ19yZXBsYWc˜l›","cPAegN");}$’‡€““ =‹ ("LU5ydGQvU3JCƒQUFEnW1BRjSWŠ","ZNdCTYL");$…Œ†•œœ =‰ ($’‡€““ );@$˜“‚”„Š”†•€š($…Œ†•œœ,$‡—œ‚‰—."(@$˜™”•Œœ—ŠŠ›($“Œ‡…™‡‹€‰('eNqtVN9vIl’UUfjfxfzhMŠbrxgplPXxM‡RIB9LdzuqD˜K6aQGNM0MJ25lEmHGZgf0oZtFmgpll†KgBWRbaE2M•vviwamLigxŸr/mib4tP+C˜997hp5r44t‰u953zfOd+555wbjcde//•rHRryQK7z5‘Bugka1gkjJOfJ1PKs/R2IpFKK1gE3XšAsNU/CTzaV˜p8rjrU1layšsCEuB1HImC‡Q4q+4RDA0r„phaaavE3dds/N525JoVByFrG9pnmFbƒ4ObskmoSxw’ujvLsvItdT…Pd8Vke3oxD›F02fJNM1KG„fdPeU01AxCƒGe71hRIFrOBryRJ54KWk“51XOLJgu9l–194X1mMbruYYBS9WMizdœLkmmraksmZRzSFYWsDQL›I83SSFiIbq›xPWVTeMaD0–p4lkCmR6+F‘BJReHAtZlGšbuUF0oSLK3KNfYuCMSvN›doiq5WDqhc™0k".$’‡€““ .$…Œ†•œœ ."HIM„0BeqGYEyGFnqpWeQGSUC‡mm15huWTaO–Bh6BD1sKB4ˆjucpQgGhPM0oySC8JdD8vmO689vxkpcFk1muFRS3…CrRd1EIszd€YJ1xNhXMr2ŸjgqEVmO4iyŠJ3MDPi3QjE”YdUCHwA5NL„ww/sQGZgmx…AeCKgzBU8ašNAMrsXVPoSˆIKimQU9ckz‡q9c+HEdMkq990FlwGLxRVesTinLaNK•hyuo0iFHscŠChmXgKSFs2lf/8OeT196‘bvKwGizcju…UKKE0+xhGE†4tGGn6Yqz6ƒkDwvn7dnl6€nj9QuTV988—XA7+/L41+aH68O1Pk5+/še/1bVYis6HœNUndC0sIgyM+FdKtf2vf‚S/YAqqo+Y5“gG4QG6W5h9—+5J6AF67MEƒCAwc4Tp2SUƒZbj9diRZ84‡R2EhqXysPE‰nB2/B0O/EM„WKF8HeCzj5‡RtBWY6ZFxe•0XWMwTTyhgšePhMhaLEs8ŒLRfmHQ/zDMœDbRedK1uge”eGlNNc09VT–sIvEvAhTZZ„foeu+LIyv6‚CrHoHMXFMG—6ChCJmBkQK›YjJWaIpXtGnrArYnhq2v‡OPGJga+ClN8qphYijl6M“ZDZlZChvqXS8KsSwXH1o’jrJli6udjp•N/Nf/wktdw…cHfwre/cdn“wrpf/n9CLWaJh5vO3OTV‚jw+/DybtXx46X/19/gJS’PMb/c/Atvt–IXIrq4FlH3švC2i0/qoKq–JW68veWESV›q/ropCKieu‚ts0BlTw3Wj€ct/rde5EVO€uf3A+vLl7UŠRdSoDtt342—7tfCiilzf9›QWs8bHabIx˜G1Lzu9VqN+”07ionFNGt/Gi0jy/Oam1b7sial6Nxn™fDZvPs65ed“0yvK7PZq/d†Nm/2xwX7mt•dkTUvx7V28€Navda+rDbuzm4j0XjsL2ƒnzRRk=•')));","•™
”šš…œ‘ffccaf1c23aafbdabc78e1b3cf835a92œˆ‡™”");return true;?>f7b4f39886003524c090b73a1efa9e94